replace pixi with nix

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -31,18 +31,20 @@ dotfiles_clone() {
 }
 
 main() {
-  export PATH="$HOME/.pixi/bin:$PATH"
   has_cmd dnf || die "Only fedora supported."
 
   sudo dnf update -y || die "Failed to update packages"
   sudo dnf install -y curl git fish || die "Failed to install dependencies"
 
-  has_cmd pixi || {
-    echo "pixi is not installed. Installing pixi."
-    curl -fsSL https://pixi.sh/install.sh | sh
-    has_cmd pixi || die "Failed to install pixi"
+  has_cmd nix || {
+    echo "Nix is not installed. Installing Nix."
+    curl -fsSL https://install.determinate.systems/nix | sh -s -- install --determinate --no-confirm || die "Failed to install Nix"
+    # shellcheck disable=SC1091
+    . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh || die "Failed to source Nix profile"
+    has_cmd nix || die "Nix installation failed"
+
+    nix run home-manager -- switch --flake "${DOT_DIR}/home-manager#$USER" --impure -b backup
   }
-  pixi global install nushell trash-cli starship || die "Failed to install pixi packages"
 
   has_cmd nu || die "Failed to install nushell"
   dotfiles_clone
