improve setup script

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -32,19 +32,21 @@ dotfiles_clone() {
 
 main() {
   export PATH="$HOME/.pixi/bin:$PATH"
+  has_cmd dnf || die "Only fedora supported."
+
+  sudo dnf update -y || die "Failed to update packages"
+  sudo dnf install -y curl git fish || die "Failed to install dependencies"
 
   has_cmd pixi || {
     echo "pixi is not installed. Installing pixi."
     curl -fsSL https://pixi.sh/install.sh | sh
     has_cmd pixi || die "Failed to install pixi"
   }
-  pixi global install nushell trash-cli
+  pixi global install nushell trash-cli starship || die "Failed to install pixi packages"
+
   has_cmd nu || die "Failed to install nushell"
-
-  has_cmd git || sudo dnf install -y git || die "Failed to install git"
   dotfiles_clone
-
-  nu "$DOT_DIR/setup.nu" fish
+  nu "$DOT_DIR/setup.nu" fish config
 }
 
 main "$@"
